accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views




app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),  # Hier wird der logout-Name definiert
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_detail/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart_item/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    
    path('get_total_price/', views.get_total_price, name='get_total_price'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('order-list/', views.order_list, name='order_list'), 
    path('checkout_view/', views.checkout_view, name='checkout_view'),  # Definieren des checkout-URLs
    path('order-summary/', views.order_summary, name='order_summary'),
    path('order-detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('update_order_status', views.update_order_status, name='update_order_status'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('success/', views.order_success, name='order_success'),
    path('checkout_address_view/', views.checkout_address_view, name='checkout_address_view')
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('categories/', views.category_list_view, name='category_list'),
]

shopping_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home_view, name='home'),
    path("contact/", views.contact_view, name='contact'),
    path("accounts/", include("accounts.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
    path("payments/", include("payments.urls")),
    path("shop/", include("shop.urls")),
    path('login/', auth_views.LoginView.as_view(), name='login'),  # Standard-Login
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # Standard-Logout
    path('profile/', auth_views.LogoutView.as_view(), name='profile'), 
    path('about/', views.about_view, name='about'), 
    path('danke/', views.danken_view, name='danke'),
    path('accounts/', include('django.contrib.auth.urls')), 

] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">Über uns</h1>
    <p class="text-center">Erfahren Sie mehr über unser Unternehmen, unsere Mission und unsere Werte.</p>

    <div class="row mt-4">
        <div class="col-md-6">
            <h3>Unsere Geschichte</h3>
            <p>
                Wir sind ein führendes E-Commerce-Unternehmen, das gegründet wurde, um Kunden weltweit die besten
                Produkte und den besten Service zu bieten.
                Seit unserer Gründung im Jahr 2020 haben wir uns auf Innovation, Qualität und Kundenzufriedenheit
                konzentriert.
            </p>
            <p>
                Unser Ziel ist es, das Einkaufserlebnis so angenehm und einfach wie möglich zu gestalten. Von Mode bis
                Technik – wir haben eine breite Palette von Produkten, die den unterschiedlichen Bedürfnissen unserer
                Kunden gerecht werden.
            </p>
        </div>
        <div class="col-md-6">
            <img width="600" height="300" src="{% static 'logo.webp' %}" alt="Unser Team">
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-6">
            <img width="600" height="300"  src="{% static 'vision.jpg' %}" alt="Unser Vision">
        </div>
        <div class="col-md-6">
            <h3>Unsere Mission und Vision</h3>
            <p>
                Unser Unternehmen ist bestrebt, das beste Einkaufserlebnis zu bieten, indem wir qualitativ hochwertige
                Produkte und außergewöhnlichen Kundenservice bereitstellen.
                Unsere Vision ist es, in der Welt des Online-Handels führend zu sein und gleichzeitig nachhaltige
                Geschäftspraktiken zu fördern.
            </p>
            <p>
                Wir arbeiten kontinuierlich daran, uns zu verbessern, indem wir innovative Technologien einsetzen, um
                den Einkaufsprozess effizienter und angenehmer zu gestalten.
                Unser Fokus liegt auf Nachhaltigkeit, Kundenzufriedenheit und einer globalen Reichweite.
            </p>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-12 text-center">
            <h3>Unser Team</h3>
            <p>
                Unser Team besteht aus engagierten Fachleuten, die leidenschaftlich daran arbeiten, Ihnen die besten
                Produkte und Dienstleistungen anzubieten.
                Wir glauben an die Kraft der Zusammenarbeit und an die stetige Weiterentwicklung, um Ihnen das Beste zu
                bieten.
            </p>
            <div class="mb-4">
                <a href="{% url 'contact' %}" class="btn btn-primary">Kontaktieren Sie uns</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}TeyiSomadje_Shop{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://js.stripe.com/v3/"></script>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img width="75px" src="{% static 'img/logo.webp' %}" alt="bild">TEYISOMADJE SHOPPING
            </a>
            
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">ABOUT US</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'shop:product_list' %}">SHOP</a></li>

                    <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">CONTACT</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">REGISTER</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'cart:cart_detail' %}">CART</a></li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'category_list' %}active{% endif %}"
                            href="{% url 'shop:category_list' %}">CATEGORIES</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'orders:order_list' %}">ORDERS</a></li>

                    {% if user.is_authenticated %}

                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:profile' %}">PROFILE</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="bg-dark text-white text-center py-3 mt-5">
        &copy; {{ 2025 }} TeyiSomadje_Shopping. All Rights Reserved.
    </footer>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/contact.html
{% extends "base.html" %}

{% block title %}Kontakt Seite{% endblock %}


{% block content %} 

<div class="container mt-5">
    <h1 class="text-center">Kontaktieren Sie uns</h1>
    <p class="text-center">Haben Sie Fragen oder benötigen Sie Hilfe? Füllen Sie das untenstehende Formular aus, und wir
        werden uns so schnell wie möglich bei Ihnen melden.</p>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Ihr Name</label>
                    <input type="text" class="form-control" id="name" name="name" required
                        placeholder="Geben Sie Ihren Namen ein">
                </div>
                <div class="form-group">
                    <label for="email">Ihre E-Mail-Adresse</label>
                    <input type="email" class="form-control" id="email" name="email" required
                        placeholder="Geben Sie Ihre E-Mail-Adresse ein">
                </div>
                <div class="form-group">
                    <label for="message">Nachricht</label>
                    <textarea class="form-control" id="message" name="message" rows="5" required
                        placeholder="Geben Sie hier Ihre Nachricht ein"></textarea>
                </div>
                <div class="my-4" my >
                    <a href="{% url 'danke' %}" type="submit" class="btn btn-primary btn-block">Nachricht senden
                    </a>
                </div>
            </form>
        </div>
    </div>

    {% if message_sent %}
    <div class="alert alert-success mt-4">
        Vielen Dank für Ihre Nachricht! Wir werden uns in Kürze bei Ihnen melden.
    </div>
    {% endif %}
</div>
















{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="text-center">
        <h1 class="text-center">Welcome to our shopping platform!</h1>
        <p class="text-center">Browse our ninth products and offers:</p>
        <a href="{% url 'shop:product_list' %}" type="button" class="my-4 btn btn-primary">Products</a>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-6 mb-4">
            <img class="w-100" src="{% get_media_prefix %}/products/cart.jpg" alt="Platform Image">
        </div>
        <div class="col-lg-6 text-justify">

            <h2>Our Vision</h2>
            <hr class="my-4">
            <p class="lead">
                Unser Unternehmen ist bestrebt, das beste Einkaufserlebnis zu bieten, indem wir qualitativ hochwertige
                Produkte
                und außergewöhnlichen Kundenservice bereitstellen. Unsere Vision ist es, in der Welt des Online-Handels
                führend zu sein und gleichzeitig nachhaltige Geschäftspraktiken zu fördern.

                Wir arbeiten kontinuierlich daran, uns zu verbessern, indem wir innovative Technologien einsetzen, um
                den
                Einkaufsprozess effizienter und angenehmer zu gestalten.
                Unser Fokus liegt auf Nachhaltigkeit, Kundenzufriedenheit und einer globalen Reichweite.

            </p>

        </div>
    </div>
</div>


{% endblock %}